[project]
name = "pii-eval-awareness"
version = "0.0.0"
description = "Scaffold for evaluation-awareness PII redaction red-teaming (no code yet)."
readme = "README.md"
license = {text = "Apache-2.0"}
requires-python = ">=3.10"

[tool.pii_eval_awareness]
status = "scaffold-only"
