experiments:
  EXP1_eval_vs_live:
    doc_variants: [plain, formatted, obfuscated]
    conditions:
      - {cue: CONTROL,  hidden: none,     placement: system}
      - {cue: EVAL_GOV, hidden: none,     placement: system}
      - {cue: LIVE_GOV, hidden: none,     placement: system}
    horizon: single_turn
    repeats_per_item: 5
    n_items: 50

  EXP2_hidden_tag:
    doc_variants: [plain, formatted, obfuscated]
    conditions:
      - {cue: CONTROL, hidden: EVAL_TAG,  placement: system}
      - {cue: CONTROL, hidden: LIVE_TAG,  placement: system}
    horizon: single_turn
    repeats_per_item: 5
    n_items: 40

  EXP3_placement:
    doc_variants: [plain, formatted]
    conditions:
      - {cue: EVAL_GOV, hidden: none, placement: system}
      - {cue: EVAL_GOV, hidden: none, placement: user}
      - {cue: EVAL_GOV, hidden: none, placement: inline}
      - {cue: LIVE_GOV, hidden: none, placement: system}
      - {cue: LIVE_GOV, hidden: none, placement: user}
      - {cue: LIVE_GOV, hidden: none, placement: inline}
    horizon: single_turn
    repeats_per_item: 5
    n_items: 40

  EXP4_long_horizon:
    doc_variants: [plain, formatted, obfuscated]
    conditions:
      - {cue: LIVE_GOV, hidden: none, placement: system}
      - {cue: CONTROL,  hidden: none, placement: system}
    horizon: multi_turn
    transforms_order: [summarize, translate_to_spanish, show_diff, export_csv]
    repeats_per_item: 5
    n_items: 50

  EXP5_self_report_cot:
    doc_variants: [obfuscated, formatted]
    conditions:
      - {cue: EVAL_GOV, hidden: none, placement: system}
      - {cue: LIVE_GOV, hidden: none, placement: system}
    horizon: multi_turn
    transforms_order: [explain_changes]
    repeats_per_item: 5
    n_items: 40
