backend: colab
model_name: gpt-oss-20b
parameters:
  temperature: 0.2
  top_p: 0.95
  max_tokens: 2048
  stop: []
reproducibility:
  seeds: [0,1,2,3,4]
  fixed_decoding: true
environment:
  endpoint: google-colab-local
  capture_gpu: true
  capture_pip: true
